name: Build (MSBuild .vcxproj)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: true
          vcpkgGitURL: 'https://github.com/microsoft/vcpkg'
          # TODO: Make this dynamic
          vcpkgGitCommitId: b1b19307e2d2ec1eefbdb7ea069de7d4bcd31f01

      - name: Build vlr-util (Release)
        run: msbuild vlr-util\vlr-util.vcxproj /p:Configuration=Release /p:Platform=x64 /m

      - name: Build vlr-util.test (Release)
        run: msbuild vlr-util.test\vlr-util.test.vcxproj /p:Configuration=Release /p:Platform=x64 /m

      - name: Run unit tests and collect results (gtest)
        run: |
          .\vlr-util.test\Release\vlr-util.test.exe --gtest_output=xml:test-results.xml
        continue-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: gtest-results
          path: test-results.xml
